/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionNewRouteImport } from './routes/transaction/new'
import { Route as TransactionGroupIdRouteImport } from './routes/transaction/$groupId'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionNewRoute = TransactionNewRouteImport.update({
  id: '/transaction/new',
  path: '/transaction/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionGroupIdRoute = TransactionGroupIdRouteImport.update({
  id: '/transaction/$groupId',
  path: '/transaction/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/farmer': typeof FarmerRoute
  '/products': typeof ProductsRoute
  '/transactions': typeof TransactionsRoute
  '/transaction/$groupId': typeof TransactionGroupIdRoute
  '/transaction/new': typeof TransactionNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/farmer': typeof FarmerRoute
  '/products': typeof ProductsRoute
  '/transactions': typeof TransactionsRoute
  '/transaction/$groupId': typeof TransactionGroupIdRoute
  '/transaction/new': typeof TransactionNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/farmer': typeof FarmerRoute
  '/products': typeof ProductsRoute
  '/transactions': typeof TransactionsRoute
  '/transaction/$groupId': typeof TransactionGroupIdRoute
  '/transaction/new': typeof TransactionNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/farmer'
    | '/products'
    | '/transactions'
    | '/transaction/$groupId'
    | '/transaction/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/farmer'
    | '/products'
    | '/transactions'
    | '/transaction/$groupId'
    | '/transaction/new'
  id:
    | '__root__'
    | '/'
    | '/farmer'
    | '/products'
    | '/transactions'
    | '/transaction/$groupId'
    | '/transaction/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FarmerRoute: typeof FarmerRoute
  ProductsRoute: typeof ProductsRoute
  TransactionsRoute: typeof TransactionsRoute
  TransactionGroupIdRoute: typeof TransactionGroupIdRoute
  TransactionNewRoute: typeof TransactionNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/new': {
      id: '/transaction/new'
      path: '/transaction/new'
      fullPath: '/transaction/new'
      preLoaderRoute: typeof TransactionNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/$groupId': {
      id: '/transaction/$groupId'
      path: '/transaction/$groupId'
      fullPath: '/transaction/$groupId'
      preLoaderRoute: typeof TransactionGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FarmerRoute: FarmerRoute,
  ProductsRoute: ProductsRoute,
  TransactionsRoute: TransactionsRoute,
  TransactionGroupIdRoute: TransactionGroupIdRoute,
  TransactionNewRoute: TransactionNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
